/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ping.proto */

#ifndef PROTOBUF_C_ping_2eproto__INCLUDED
#define PROTOBUF_C_ping_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Ping Ping;


/* --- enums --- */


/* --- messages --- */

struct  Ping
{
  ProtobufCMessage base;
  char *message;
};
#define PING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ping__descriptor) \
    , (char *)protobuf_c_empty_string }


/* Ping methods */
void   ping__init
                     (Ping         *message);
size_t ping__get_packed_size
                     (const Ping   *message);
size_t ping__pack
                     (const Ping   *message,
                      uint8_t             *out);
size_t ping__pack_to_buffer
                     (const Ping   *message,
                      ProtobufCBuffer     *buffer);
Ping *
       ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ping__free_unpacked
                     (Ping *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Ping_Closure)
                 (const Ping *message,
                  void *closure_data);

/* --- services --- */

typedef struct PingService_Service PingService_Service;
struct PingService_Service
{
  ProtobufCService base;
  void (*reply_to_ping)(PingService_Service *service,
                        const Ping *input,
                        Ping_Closure closure,
                        void *closure_data);
};
typedef void (*PingService_ServiceDestroy)(PingService_Service *);
void ping_service__init (PingService_Service *service,
                         PingService_ServiceDestroy destroy);
#define PING_SERVICE__BASE_INIT \
    { &ping_service__descriptor, protobuf_c_service_invoke_internal, NULL }
#define PING_SERVICE__INIT(function_prefix__) \
    { PING_SERVICE__BASE_INIT,\
      function_prefix__ ## reply_to_ping  }
void ping_service__reply_to_ping(ProtobufCService *service,
                                 const Ping *input,
                                 Ping_Closure closure,
                                 void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ping__descriptor;
extern const ProtobufCServiceDescriptor ping_service__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ping_2eproto__INCLUDED */
