/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ping.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ping.pb-c.h"
void   ping__init
                     (Ping         *message)
{
  static const Ping init_value = PING__INIT;
  *message = init_value;
}
size_t ping__get_packed_size
                     (const Ping *message)
{
  assert(message->base.descriptor == &ping__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ping__pack
                     (const Ping *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ping__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ping__pack_to_buffer
                     (const Ping *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ping__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ping *
       ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ping *)
     protobuf_c_message_unpack (&ping__descriptor,
                                allocator, len, data);
}
void   ping__free_unpacked
                     (Ping *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ping__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ping__field_descriptors[1] =
{
  {
    "message",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ping, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ping__field_indices_by_name[] = {
  0,   /* field[0] = message */
};
static const ProtobufCIntRange ping__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ping__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ping",
  "Ping",
  "Ping",
  "",
  sizeof(Ping),
  1,
  ping__field_descriptors,
  ping__field_indices_by_name,
  1,  ping__number_ranges,
  (ProtobufCMessageInit) ping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor ping_service__method_descriptors[1] =
{
  { "ReplyToPing", &ping__descriptor, &ping__descriptor },
};
const unsigned ping_service__method_indices_by_name[] = {
  0         /* ReplyToPing */
};
const ProtobufCServiceDescriptor ping_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "PingService",
  "PingService",
  "PingService",
  "",
  1,
  ping_service__method_descriptors,
  ping_service__method_indices_by_name
};
void ping_service__reply_to_ping(ProtobufCService *service,
                                 const Ping *input,
                                 Ping_Closure closure,
                                 void *closure_data)
{
  assert(service->descriptor == &ping_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void ping_service__init (PingService_Service *service,
                         PingService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &ping_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
